# File generated by GPT5.6-Luna
"""Optional Discord transition notifications."""

from __future__ import annotations

import json
import logging
import os
import time
from typing import Callable, Optional
from urllib import request

from resource_monitor import NORMAL, OVERLOADED, ResourceSnapshot

logger = logging.getLogger(__name__)

DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL", "")


class DiscordNotifier:
    def __init__(
        self,
        webhook_url: Optional[str] = None,
        cooldown_seconds: Optional[float] = None,
        timeout_seconds: float = 5.0,
        clock: Callable[[], float] = time.monotonic,
        opener: Callable[..., object] = request.urlopen,
    ) -> None:
        self.webhook_url = DISCORD_WEBHOOK_URL if webhook_url is None else webhook_url
        self.cooldown_seconds = (
            float(os.getenv("DISCORD_NOTIFICATION_COOLDOWN_SECONDS", "300"))
            if cooldown_seconds is None
            else cooldown_seconds
        )
        self.timeout_seconds = timeout_seconds
        self._clock = clock
        self._opener = opener
        self._last_sent: dict[str, float] = {}

    def notify(self, state: str, snapshot: ResourceSnapshot) -> bool:
        if state not in {NORMAL, OVERLOADED}:
            raise ValueError(f"unsupported notification state: {state}")
        if not self.webhook_url:
            logger.warning("Discord notifications are disabled: webhook is not configured")
            return False

        event = "recovery" if state == NORMAL else "overload"
        now = self._clock()
        last_sent = self._last_sent.get(event)
        if last_sent is not None and now - last_sent < self.cooldown_seconds:
            logger.info("Discord %s notification is in cooldown", event)
            return False

        payload = {
            "content": (
                f"Canvas Critic resource state: {state}. "
                f"CPU {snapshot.cpu_percent:.1f}%, memory {snapshot.memory_percent:.1f}%"
            )
        }
        body = json.dumps(payload).encode("utf-8")
        http_request = request.Request(
            self.webhook_url,
            data=body,
            headers={
                "Content-Type": "application/json",
                "Accept": "application/json",
                "User-Agent": "Canvas-Critic/1.0",
            },
            method="POST",
        )
        try:
            response = self._opener(http_request, timeout=self.timeout_seconds)
            close = getattr(response, "close", None)
            if close is not None:
                close()
        except Exception:
            logger.exception("Discord %s notification failed", event)
            return False

        self._last_sent[event] = now
        logger.info("Discord %s notification sent", event)
        return True