# File generated by GPT5.6-Luna
"""CPU and system-memory capacity monitoring for the application VM."""

from __future__ import annotations

import logging
import os
import threading
import time
from dataclasses import dataclass
from typing import Callable, Optional

try:
    import psutil
except ImportError:  # Keep import-time errors actionable in app startup.
    psutil = None

logger = logging.getLogger(__name__)

NORMAL = "NORMAL"
OVERLOADED = "OVERLOADED"


def _env_float(name: str, default: float) -> float:
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return float(value)
    except ValueError as error:
        raise ValueError(f"{name} must be a number") from error


def _env_int(name: str, default: int) -> int:
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return int(value)
    except ValueError as error:
        raise ValueError(f"{name} must be an integer") from error


@dataclass(frozen=True)
class ResourceSnapshot:
    cpu_percent: float
    memory_percent: float
    timestamp: float


@dataclass(frozen=True)
class MonitorConfig:
    interval_seconds: float = 5.0
    cpu_overload_percent: float = 90.0
    memory_overload_percent: float = 85.0
    cpu_recovery_percent: float = 70.0
    memory_recovery_percent: float = 70.0
    consecutive_samples: int = 3

    def __post_init__(self) -> None:
        if self.interval_seconds <= 0 or self.consecutive_samples <= 0:
            raise ValueError("monitor interval and consecutive samples must be positive")
        if not (
            self.cpu_recovery_percent < self.cpu_overload_percent
            and self.memory_recovery_percent < self.memory_overload_percent
        ):
            raise ValueError("recovery thresholds must be lower than overload thresholds")

    @classmethod
    def from_environment(cls) -> "MonitorConfig":
        config = cls(
            interval_seconds=_env_float("RESOURCE_MONITOR_INTERVAL_SECONDS", 5.0),
            cpu_overload_percent=_env_float("RESOURCE_CPU_OVERLOAD_PERCENT", 90.0),
            memory_overload_percent=_env_float(
                "RESOURCE_MEMORY_OVERLOAD_PERCENT", 85.0
            ),
            cpu_recovery_percent=_env_float("RESOURCE_CPU_RECOVERY_PERCENT", 70.0),
            memory_recovery_percent=_env_float(
                "RESOURCE_MEMORY_RECOVERY_PERCENT", 70.0
            ),
            consecutive_samples=_env_int("RESOURCE_CONSECUTIVE_SAMPLES", 3),
        )
        return config


class ResourceMonitorUnavailable(RuntimeError):
    """Raised when the required resource-monitoring dependency is unavailable."""


class ResourceMonitor:
    def __init__(
        self,
        config: Optional[MonitorConfig] = None,
        sampler: Optional[Callable[[], tuple[float, float]]] = None,
        clock: Callable[[], float] = time.monotonic,
        on_transition: Optional[Callable[[str, ResourceSnapshot], None]] = None,
    ) -> None:
        if sampler is None and psutil is None:
            raise ResourceMonitorUnavailable(
                "psutil is required for resource monitoring; install the declared "
                "application dependencies before starting Canvas Critic"
            )
        self.config = config or MonitorConfig.from_environment()
        self._sampler = sampler or self._sample_psutil
        self._clock = clock
        self._on_transition = on_transition
        self._state = NORMAL
        self._consecutive_overload = 0
        self._consecutive_recovery = 0
        self._lock = threading.Lock()
        self._thread: Optional[threading.Thread] = None
        self._stop_event = threading.Event()
        self._last_snapshot: Optional[ResourceSnapshot] = None

    def _sample_psutil(self) -> tuple[float, float]:
        assert psutil is not None
        return psutil.cpu_percent(interval=None), psutil.virtual_memory().percent

    def start(self) -> threading.Thread:
        with self._lock:
            if self._thread is not None and self._thread.is_alive():
                return self._thread
            self._stop_event.clear()
            if psutil is not None and self._sampler == self._sample_psutil:
                psutil.cpu_percent(interval=None)
            self._thread = threading.Thread(
                target=self._run,
                name="resource-monitor",
                daemon=True,
            )
            self._thread.start()
            return self._thread

    def stop(self) -> None:
        self._stop_event.set()

    def _run(self) -> None:
        while not self._stop_event.is_set():
            try:
                cpu_percent, memory_percent = self._sampler()
                self.update(cpu_percent, memory_percent)
            except Exception:
                logger.exception("Resource monitoring sample failed")
            self._stop_event.wait(self.config.interval_seconds)

    def update(self, cpu_percent: float, memory_percent: float) -> Optional[str]:
        snapshot = ResourceSnapshot(cpu_percent, memory_percent, self._clock())
        transition: Optional[str] = None
        with self._lock:
            self._last_snapshot = snapshot
            if self._state == NORMAL:
                if (
                    cpu_percent >= self.config.cpu_overload_percent
                    or memory_percent >= self.config.memory_overload_percent
                ):
                    self._consecutive_overload += 1
                else:
                    self._consecutive_overload = 0
                self._consecutive_recovery = 0
                if self._consecutive_overload >= self.config.consecutive_samples:
                    self._state = OVERLOADED
                    self._consecutive_overload = 0
                    transition = OVERLOADED
            else:
                if (
                    cpu_percent < self.config.cpu_recovery_percent
                    and memory_percent < self.config.memory_recovery_percent
                ):
                    self._consecutive_recovery += 1
                else:
                    self._consecutive_recovery = 0
                self._consecutive_overload = 0
                if self._consecutive_recovery >= self.config.consecutive_samples:
                    self._state = NORMAL
                    self._consecutive_recovery = 0
                    transition = NORMAL

        if transition is not None:
            logger.info(
                "Resource monitor state changed state=%s cpu_percent=%.1f memory_percent=%.1f",
                transition,
                cpu_percent,
                memory_percent,
            )
            if self._on_transition is not None:
                try:
                    self._on_transition(transition, snapshot)
                except Exception:
                    logger.exception("Resource monitor transition callback failed")
        return transition

    def state(self) -> str:
        with self._lock:
            return self._state

    def is_overloaded(self) -> bool:
        return self.state() == OVERLOADED

    def snapshot(self) -> Optional[ResourceSnapshot]:
        with self._lock:
            return self._last_snapshot