# File generated by GPT5.6-Luna
from unittest.mock import Mock

import pytest

from notifications import DiscordNotifier
from resource_monitor import (
    NORMAL,
    OVERLOADED,
    MonitorConfig,
    ResourceMonitor,
    ResourceSnapshot,
)


def make_monitor(callback=None, samples=3):
    return ResourceMonitor(
        config=MonitorConfig(
            interval_seconds=1,
            cpu_overload_percent=90,
            memory_overload_percent=85,
            cpu_recovery_percent=70,
            memory_recovery_percent=70,
            consecutive_samples=samples,
        ),
        sampler=lambda: (0, 0),
        clock=iter(range(100)).__next__,
        on_transition=callback,
    )


def test_overload_requires_sustained_high_usage():
    transitions = Mock()
    monitor = make_monitor(transitions)

    assert monitor.update(95, 20) is None
    assert monitor.update(20, 90) is None
    assert monitor.update(91, 20) == OVERLOADED
    assert monitor.is_overloaded()
    transitions.assert_called_once()


def test_isolated_spike_does_not_overload():
    monitor = make_monitor()

    monitor.update(95, 20)
    monitor.update(20, 20)
    monitor.update(95, 20)

    assert monitor.state() == NORMAL


def test_recovery_requires_both_metrics_below_lower_threshold():
    monitor = make_monitor()
    for _ in range(3):
        monitor.update(95, 20)
    assert monitor.state() == OVERLOADED

    assert monitor.update(69, 90) is None
    assert monitor.update(69, 69) is None
    assert monitor.update(69, 69) is None
    assert monitor.update(69, 69) == NORMAL
    assert monitor.state() == NORMAL


def test_notifier_has_independent_overload_and_recovery_cooldowns():
    opener = Mock(return_value=Mock())
    now = [0.0]
    notifier = DiscordNotifier(
        webhook_url="https://discord.example/webhook",
        cooldown_seconds=300,
        clock=lambda: now[0],
        opener=opener,
    )
    snapshot = ResourceSnapshot(95, 90, 0)

    assert notifier.notify(OVERLOADED, snapshot)
    assert not notifier.notify(OVERLOADED, snapshot)
    assert notifier.notify(NORMAL, snapshot)
    assert opener.call_count == 2


def test_empty_webhook_disables_notifications_without_raising():
    notifier = DiscordNotifier(webhook_url="")
    assert not notifier.notify(OVERLOADED, ResourceSnapshot(95, 90, 0))


def test_notification_failure_is_isolated():
    opener = Mock(side_effect=OSError("network down"))
    notifier = DiscordNotifier(
        webhook_url="https://discord.example/webhook", opener=opener
    )

    assert not notifier.notify(OVERLOADED, ResourceSnapshot(95, 90, 0))
    assert notifier.notify(OVERLOADED, ResourceSnapshot(95, 90, 0)) is False


def test_invalid_monitor_configuration_is_rejected():
    with pytest.raises(ValueError, match="recovery thresholds"):
        MonitorConfig(
            cpu_overload_percent=70,
            memory_overload_percent=85,
            cpu_recovery_percent=70,
            memory_recovery_percent=70,
        )